apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgresql
  namespace: ansible-tower
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: ibmc-block-gold