# Source: bookinfo/charts/ratings/templates/service-account.yaml
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: bookinfo-ratings-sa-deployable
  namespace: bookinfo-source
  labels:
    appname: bookinfo-demo
    release: bookinfo-demo
    component: ratings
    prereq: "yes"
spec:
  template:
    apiVersion: v1
    kind: ServiceAccount
    metadata:
      name: bookinfo-ratings

---
# Source: bookinfo/charts/ratings/templates/clusterrole.yaml
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: bookinfo-ratings-rbac-deployable
  namespace: bookinfo-source
  labels:
    appname: bookinfo-demo
    release: bookinfo-demo
    component: ratings
    prereq: "yes"
spec:
  template:
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRole
    metadata:
      name: ratings-lwdc-query
    rules:
    - apiGroups:
      - ""
      - apps
      resources:
      - clusters
      - nodes
      - services
      - configmaps
      - pods
      - endpoints
      - deployments
      verbs:
      - list
      - get
---
# Source: bookinfo/charts/ratings/templates/rolebinding.yaml
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: bookinfo-ratings-crb-deployable
  namespace: bookinfo-source
  labels:
    appname: bookinfo-demo
    release: bookinfo-demo
    component: ratings
    prereq: "yes"
spec:
  template:
    kind: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    metadata:
      name: ratings-lwdc-rolebinding
      namespace: bookinfo
    subjects:
    - kind: User
      name: system:serviceaccount:bookinfo:bookinfo-ratings
      apiGroup: rbac.authorization.k8s.io
    roleRef:
      kind: ClusterRole
      name: ratings-lwdc-query
      apiGroup: rbac.authorization.k8s.io
---
# Source: bookinfo/charts/ratings/templates/service.yaml
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: bookinfo-ratings-svc-deployable
  namespace: bookinfo-source
  labels:
    appname: bookinfo-demo
    release: bookinfo-demo
    component: ratings
    prereq: "no"
spec:
  template:
    apiVersion: v1
    kind: Service
    metadata:
      name: ratings
      labels:
        app.kubernetes.io/name: ratings
        app.kubernetes.io/instance: bookinfo-demo
    spec:
      ports:
        - port: 9080
          targetPort: http
          protocol: TCP
          name: http
      selector:
        app.kubernetes.io/name: ratings
        app.kubernetes.io/instance: bookinfo-demo

---
# Source: bookinfo/charts/ratings/templates/deployment.yaml
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: bookinfo-ratings-deploy-deployable
  namespace: bookinfo-source
  labels:
    appname: bookinfo-demo
    release: bookinfo-demo
    component: ratings
    prereq: "no"
spec:
  template:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: bookinfo-demo-ratings
      labels:
        app.kubernetes.io/name: ratings
        app.kubernetes.io/instance: bookinfo-demo
    spec:
      replicas: 1
      selector:
        matchLabels:
          app.kubernetes.io/name: ratings
          app.kubernetes.io/instance: bookinfo-demo
      template:
        metadata:
          labels:
            app.kubernetes.io/name: ratings
            app.kubernetes.io/instance: bookinfo-demo
        spec:
          serviceAccountName: bookinfo-ratings
          containers:
            - env:
              - name: DB_TYPE
                value: mysql
              - name: MYSQL_DB_HOST
                value: mysqldb
              - name: MYSQL_DB_PORT
                value: "3306"
              - name: MYSQL_DB_USER
                value: root
              - name: MYSQL_DB_PASSWORD
                value: password
              - name: OPENTRACING_ENABLED
                value: "true"
              - name: JAEGER_SAMPLER_TYPE
                value: probabilistic
              - name: OPENTRACING_SAMPLER
                value: "1"
              - name: LATENCY_SAMPLER_PARAM
                value: "1"
              name: ratings
              image: "docker.io/dymaczew/examples-bookinfo-ratings-v2:2020.1.0.1"
              imagePullPolicy: Always
              ports:
                - name: http
                  containerPort: 9080
                  protocol: TCP
              livenessProbe:
                httpGet:
                  path: /health
                  port: http
              readinessProbe:
                httpGet:
                  path: /health
                  port: http
              volumeMounts:
              - mountPath: /opt/ibm/apm/serverconfig
                name: global-environment
              resources:
                {}                
          volumes:
          - name: global-environment
            secret:
              defaultMode: 420
              optional: true
              secretName: icam-server-secret

