# Source: bookinfo/charts/reviews/templates/service-account.yaml
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: bookinfo-create-load-deployable
  namespace: bookinfo-source
  labels:
    appname: bookinfo-demo
    release: bookinfo-demo
    component: productpage
    prereq: "yes"
spec:
  template:
    apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: bookinfo-create-load
      namespace: default
      labels:
          app: bookinfo-create-load
    spec:
      replicas: 0
      selector:
        matchLabels:
          app: bookinfo-create-load
      template:
        metadata:
          labels:
            app: bookinfo-create-load
        spec:
          containers:
          - image: niklaushirt/tools:1.0.1
            imagePullPolicy: IfNotPresent
            name: alpine
            command:
              - /bin/sh
              - "-c"
              - "ab -n 100000000 -c 100 -v 5 http://productpage.bookinfo.svc.cluster.local:9080/"
            ports:
            - containerPort: 3000
            resources:
              requests:
                cpu: "50m"
                memory: "50Mi"
              limits:
                cpu: "50m"
                memory: "50Mi"
            env:
              - name: PORT
                value : "3000"
---
apiVersion: app.ibm.com/v1alpha1
kind: Deployable
metadata:
  annotations:
    app.ibm.com/is-local-deployable: "false"
  name: bookinfo-ingress-deployable
  namespace: bookinfo-source
  labels:
    appname: bookinfo-demo
    release: bookinfo-demo
    component: productpage
    prereq: "yes"
spec:
  template:
    kind: Ingress
    apiVersion: networking.k8s.io/v1beta1
    metadata:
      name: modresort-app-web-ingress
      namespace: bookinfo
      labels:
        app: modresort-app-web
    spec:
      rules:
        - http:
            paths:
              - path: /resort
                backend:
                  serviceName: modresort-app-web-service
                  servicePort: 9080
    status:
      loadBalancer: {}
