apiVersion: charts.helm.k8s.io/v1alpha1
kind: Xl
metadata:
  name: xl-release
  labels:
    app.kubernetes.io/name: t8c-operator
    app.kubernetes.io/instance: t8c-operator
    app.kubernetes.io/managed-by: operator-life
spec:
  # Default values copied from <project_dir>/helm-charts/xl/values.yaml

  # Default values for xl.
  # This is a YAML-formatted file.
  # Declare variables to be passed into your templates.

  # Any changes run : kubectl apply -f turbonomics/charts_v1alpha1_xl_cr_ibm.yaml -n turbonomic

  # Global settings
  global:
  #  registry: index.docker.io
  #  imageUsername: turbouser
  #  imagePassword: turbopassword
    repository: turbonomic
    tag: 7.22.0
#    externalDBName: t8c-ibm.chlurvxzsi3a.us-east-1.rds.amazonaws.com
    securityContext:
      fsGroup: 0
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
            - matchExpressions:
              - key: beta.kubernetes.io/arch
                operator: In
                values:
                  - amd64
    annotations:
      productName: Turbonomic Application Resource Management Platform
      productID: TurbonomicPlatform_7.22.0
      productVersion: 7.22.0
#  api:
#    resources:
#      limits:
#        cpu: 1000m
#        memory: 6Gi
#      requests:
#        cpu: 100m
#        memory: 128Mi
#  market:
#    resources:
#      limits:
#        cpu: 1000m
#        memory: 6Gi
#      requests:
#        cpu: 100m
#        memory: 128Mi
#  clustermgr:
#    image:
#      pullPolicy: Always

  nginxingress:
    enabled: true
  kubeturbo:
    enabled: false

  # Component selector - Probes
  actionscript:
    enabled: true
  aix:
    enabled: true
  appdynamics:
    enabled: true
  appinsights:
    enabled: true
  aws:
    enabled: true
  baremetal:
    enabled: true
  datadog:
    enabled: true
  awslambda:
    enabled: true
  azure:
    enabled: true
  cloudfoundry:
    enabled: true
  compellent:
    enabled: true
  dynatrace:
    enabled: true
  gcp:
    enabled: true
  hpe3par:
    enabled: true
  hds:
    enabled: true
  horizon:
    enabled: true
  hyperflex:
    enabled: true
  hyperv:
    enabled: true
  intersight:
    enabled: true
  istio:
    enabled: true
  mssql:
    enabled: true
  netapp:
    enabled: true
  netflow:
    enabled: true
  newrelic:
    enabled: true
  oneview:
    enabled: true
  openstack:
    enabled: true
  pivotal:
    enabled: true
  pure:
    enabled: true
  rhv:
    enabled: true
  scaleio:
    enabled: true
  snmp:
    enabled: true
  terraform:
    enabled: true
  tetration:
    enabled: true
  ucs:
    enabled: true
  ucsdirector:
    enabled: true
  vcd:
    enabled: true
  vcenter:
    enabled: true
  vmax:
    enabled: true
  vmm:
    enabled: true
  vplex:
    enabled: true
  wmi:
    enabled: true
  xtremio:
    enabled: true
