apiVersion: orchestrator.management.ibm.com/v1alpha1
kind: Installation
metadata:
  name: management-installation
  namespace: <NAMESPACE>
spec:
  storageClass: '<STORAGE_CLASS>'
  imagePullSecret: ibm-management-pull-secret
  license:
    accept: true
  mcmCoreDisabled: <DISABLE_MCM_CORE_INSTALL>
  pakModules:
    - config:
        - enabled: false
          name: ibm-management-im-install
          spec: {}
        - enabled: false
          name: ibm-management-infra-grc
          spec: {}
        - enabled: false
          name: ibm-management-infra-vm
          spec: {}
        - enabled: false
          name: ibm-management-cam-install
          spec: {}
        - enabled: false
          name: ibm-management-service-library
          spec: {}
      enabled: false
      name: infrastructureManagement
    - config:
        - enabled: false
          name: ibm-management-monitoring
          spec:
            operandRequest: {}
            monitoringDeploy:
              global:
                environmentSize: size0
                persistence:
                  storageClassOption:
                    cassandrabak: none
                    cassandradata: default
                    couchdbdata: default
                    datalayerjobs: default
                    elasticdata: default
                    kafkadata: default
                    zookeeperdata: default
                  storageSize:
                    cassandrabak: 50Gi
                    cassandradata: 50Gi
                    couchdbdata: 5Gi
                    datalayerjobs: 5Gi
                    elasticdata: 5Gi
                    kafkadata: 10Gi
                    zookeeperdata: 1Gi
      enabled: false
      name: monitoring
    - config:
        - enabled: false
          name: ibm-management-notary
          spec: {}
        - enabled: false
          name: ibm-management-image-security-enforcement
          spec: {}
        - enabled: false
          name: ibm-management-mutation-advisor
          spec: {}
        - enabled: false
          name: ibm-management-vulnerability-advisor
          spec:
            controlplane:
              esSecurityEnabled: true
              esServiceName: elasticsearch.ibm-common-services
              esSecretName: logging-elk-certs
              esSecretCA: ca.crt
              esSecretCert: curator.crt
              esSecretKey: curator.key
            annotator:
              esSecurityEnabled: true
              esServiceName: elasticsearch.ibm-common-services
              esSecretName: logging-elk-certs
              esSecretCA: ca.crt
              esSecretCert: curator.crt
              esSecretKey: curator.key
            indexer:
              esSecurityEnabled: true
              esServiceName: elasticsearch.ibm-common-services
              esSecretName: logging-elk-certs
              esSecretCA: ca.crt
              esSecretCert: curator.crt
              esSecretKey: curator.key
      enabled: false
      name: securityServices
    - config:
        - enabled: false
          name: ibm-management-sre-chatops
          spec: {}
      enabled: false
      name: operations
    - config:
        - enabled: false
          name: ibm-management-manage-runtime
          spec: {}
      enabled: false
      name: techPreview
