apiVersion: orchestrator.management.ibm.com/v1alpha1
kind: Installation
metadata:
  name: management-installation
  namespace: <NAMESPACE>
spec:
  storageClass: '<STORAGE_CLASS>'
  imagePullSecret: ibm-management-pull-secret
  license:
    accept: true
  mcmCoreDisabled: <DISABLE_MCM_CORE_INSTALL>
  pakModules:
    - config:
        - enabled: <INSTALL_INFRA_VM>
          name: ibm-management-im-install
          spec: {}
        - enabled: <INSTALL_INFRA_GRC>
          name: ibm-management-infra-grc
          spec: {}
        - enabled: <INSTALL_INFRA_VM>
          name: ibm-management-infra-vm
          spec: {}
        - enabled: <INSTALL_INFRA_CAM>
          name: ibm-management-cam-install
          spec:
            manageservice:
              roks: true
              camLogsPV:
                persistence:
                  #enabled: false
                  storageClassName: ibmc-file-gold
              camMongoPV:
                persistence:
                  #enabled: false
                  storageClassName: ibmc-block-gold
                  accessMode: ReadWriteOnce
              camTerraformPV:
                persistence:
                  #enabled: false
                  storageClassName: ibmc-file-gold                  
        - enabled: <INSTALL_INFRA_SERVICE_LIBRARY>
          name: ibm-management-service-library
          spec: {}
      enabled: <INSTALL_BLOCK_INFRA>
      name: infrastructureManagement
    - config:
        - enabled: <INSTALL_MON_MONITORING>
          name: ibm-management-monitoring
          spec:
            operandRequest: {}
            monitoringDeploy:
              global:
                environmentSize: size0
                persistence:
                  storageClassOption:
                    cassandrabak: none
                    cassandradata: default
                    couchdbdata: default
                    datalayerjobs: default
                    elasticdata: default
                    kafkadata: default
                    zookeeperdata: default
                  storageSize:
                    cassandrabak: 50Gi
                    cassandradata: 50Gi
                    couchdbdata: 5Gi
                    datalayerjobs: 5Gi
                    elasticdata: 5Gi
                    kafkadata: 10Gi
                    zookeeperdata: 1Gi
      enabled: <INSTALL_BLOCK_MON>
      name: monitoring
    - config:
        - enabled: <INSTALL_MCMNOT>
          name: ibm-management-notary
          spec: {}
        - enabled: <INSTALL_MCMIMGSEC>
          name: ibm-management-image-security-enforcement
          spec: {}
        - enabled: <INSTALL_MCMMUT>
          name: ibm-management-mutation-advisor
          spec: {}
        - enabled: <INSTALL_MCMVUL>
          name: ibm-management-vulnerability-advisor
          spec:
            controlplane:
              esSecurityEnabled: true
              esServiceName: elasticsearch.ibm-common-services
              esSecretName: logging-elk-certs
              esSecretCA: ca.crt
              esSecretCert: curator.crt
              esSecretKey: curator.key
            annotator:
              esSecurityEnabled: true
              esServiceName: elasticsearch.ibm-common-services
              esSecretName: logging-elk-certs
              esSecretCA: ca.crt
              esSecretCert: curator.crt
              esSecretKey: curator.key
            indexer:
              esSecurityEnabled: true
              esServiceName: elasticsearch.ibm-common-services
              esSecretName: logging-elk-certs
              esSecretCA: ca.crt
              esSecretCert: curator.crt
              esSecretKey: curator.key
      enabled: <INSTALL_BLOCK_SEC>
      name: securityServices
    - config:
        - enabled: <INSTALL_OPS_CHAT>
          name: ibm-management-sre-chatops
          spec: {}
      enabled: <INSTALL_BLOCK_OPS>
      name: operations
    - config:
        - enabled: <INSTALL_TP_MNG_RT>
          name: ibm-management-manage-runtime
          spec: {}
      enabled: <INSTALL_BLOCK_TP>
      name: techPreview
