kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cam-terraform-pv
  namespace: management-infrastructure-management
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: ibmc-file-gold
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cam-mongo-pv
  namespace: management-infrastructure-management
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: ibmc-file-gold
  volumeMode: Filesystem
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cam-logs-pv
  namespace: management-infrastructure-management
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
  storageClassName: ibmc-file-gold
  volumeMode: Filesystem