
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: pacman
  namespace: pacman-app
  generation: 1
  labels:
    app: pacman
spec:
  componentKinds:
    - group: app.ibm.com
      kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - pacman
