apiVersion: app.ibm.com/v1alpha1
kind: Subscription
metadata:
  name: pacman-web
  namespace: pacman-app
  generation: 1
  labels:
    app: pacman
spec:
  name: ''
  channel: pacman-ns/pacman-channel
  placement:
    placementRef:
      name: pacman-web-placement
      kind: PlacementRule
  packageFilter:
    labelSelector:
      matchLabels:
        app: pacman
---
apiVersion: app.ibm.com/v1alpha1
kind: PlacementRule
metadata:
  name: pacman-web-placement
  namespace: pacman-app
  generation: 1
  labels:
    app: pacman
spec:
  clusterLabels:
    matchLabels:
      environment: Prod
      region: EU
  clusterReplicas: 2
