#kubectl create ns cloud-university-app
#kubectl create ns cloud-university-app-channel


apiVersion: v1
kind: Namespace
metadata:
  name: pacman-app
---
apiVersion: v1
kind: Namespace
metadata:
  name: pacman-ns

